trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

jobs:
- template: 'django-basic/azure-pipelines.yml'
- template: 'django-multi-environment/azure-pipelines.yml'
- template: 'flask-basic/azure-pipelines.yml'
- template: 'library-basic/azure-pipelines.yml'
- template: 'library-flit/azure-pipelines.yml'