name: 'my pipeline'
stages:   

  - stage: test    
    pool:      
      vmImage: 'macOS-latest'
    jobs:
      - job: myJob
        steps:
          - script: | 
              echo 'aaaaaaa'
            displayName: 'ececute script'
          - task: UsePythonVersion@0
            displayName: 'use python 3.0'
            inputs:
              versionSpec: '3.6'
          - task: PythonScript@0
            displayName: 'execute python'
            inputs:
                scriptSource: inline
                script: | 
                  print('python app...')
                        